language: csharp
solution: BudgetCli.sln
mono: none
dotnet: 3.0.101

before_install:
 - sudo apt-get install jq
 - curl -LSs $(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test

after_success:
 - java -jar codacy-coverage-reporter-assembly.jar report -l CSharp