language: csharp
solution: BudgetCli.sln
mono: none
dotnet: 3.0.101

before_script:
 - export PATH=$PATH:/home/travis/.dotnet/tools

before_install:
 - sudo apt-get install jq
 - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
 - dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.4.6.0
 - mkdir coveragereport

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test "./" "/p:CollectCoverage=true" "/p:CoverletOutputFormat=lcov" "/p:CoverletOutput=./lcov.info"

after_success:
 - reportgenerator  "-reports:BudgetCli.*.Tests/lcov.info" "-targetdir:coveragereport" "-reporttypes:lcov" "-filefilters:-*\Budget-CLI\BudgetCli.*.Tests\*;-*Generated*;-*.nuget*"
 - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l csharp -r coveragereport/lcov.info --force-language --commit-uuid $TRAVIS_COMMIT